// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgtzmujlwwmkyflxmlvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNndHptdWpsd3dta3lmbHhtbHZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODExODQsImV4cCI6MjA2NTY1NzE4NH0.65piELcibZ-1dmxPZjH-jNUOwBXyL9fyphkgnJJA9IU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);